before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./hack/make/completions
    - ./hack/make/manpages
    - ./hack/make/json_mini

snapshot:
  name_template: '{{ incpatch .Version }}-next'

builds:
  - id: darwin
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - id: darwin_extras
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/opt/homebrew/lib
      - CGO_CFLAGS=-I/opt/homebrew/include
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - libusb
      - unicorn
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - id: ios
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
      - CC=$GOROOT/misc/ios/clangwrap.sh
    goos:
      - ios
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
    hooks:
      post: ./hack/make/codesign {{ .Path }}
  - id: linux-amd64
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - id: linux-arm64
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - id: windows
    main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}

universal_binaries:
  - id: darwin
    replace: false

archives:
  - replacements:
      darwin: macOS
      ios: iOS
      amd64: x86_64
      all: universal
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*
    wrap_in_directory: true

brews:
  - tap:
      owner: blacktop
      name: homebrew-tap
    ids:
        - darwin_extras
    folder: Formula
    homepage: "https://github.com/blacktop/ipsw"
    description: "iOS/macOS Research Swiss Army Knife"
    license: MIT
    dependencies:
      - name: bat
        type: optional
      - name: libusb
      - name: unicorn
    install: |
      bin.install "ipsw"
      bash_completion.install "completions/_bash" => "ipsw"
      zsh_completion.install "completions/_zsh" => "_ipsw"
      fish_completion.install "completions/_fish" => "ipsw.fish"
      man1.install Dir["manpages/*"]
    test: |
      system "#{bin}/ipsw --version"
checksum:
  name_template: "checksums.darwin.txt"

nfpms:
  - id: packages
    builds:
      - linux-amd64
      - linux-arm64
    homepage:  https://github.com/blacktop/ipsw
    description: |-
      iOS/macOS Research Swiss Army Knife.
    maintainer: Blacktop <https://github.com/blacktop>
    license: MIT
    vendor: Blacktop
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/_bash
        dst: /usr/share/bash-completion/completions/ipsw
        file_info:
          mode: 0644
      - src: ./completions/_fish
        dst: /usr/share/fish/completions/ipsw.fish
        file_info:
          mode: 0644
      - src: ./completions/_zsh
        dst:  /usr/share/zsh/vendor-completions/_ipsw
        file_info:
          mode: 0644
      - src: ./manpages/ipsw.1.gz
        dst: /usr/share/man/man1/ipsw.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/ipsw/copyright
        file_info:
          mode: 0644
    replacements:
      amd64: x86_64
    formats:
    - apk
    - deb
    - rpm

snapcrafts:
  - id: snaps
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
    - linux-amd64
    - linux-arm64
    summary: iOS/macOS Research Swiss Army Knife.
    description: |
      iOS/macOS Research Swiss Army Knife.
    grade: stable
    confinement: strict
    publish: true
    license: MIT

scoop:
  bucket:
    owner: blacktop
    name: scoop-bucket
    token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
  homepage:  https://blacktop.github.io/ipsw
  description: iOS/macOS Research Swiss Army Knife
  license: MIT

signs:
  - artifacts: checksum

sboms:
  - artifacts: archive

changelog:
  sort: asc
  use: github
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: Dependency updates
      regexp: "^.*chore\\(deps\\)*:+.*$"
      order: 300
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "^Delete"
      - "^Working"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/ipsw/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Read the [documentation](https://blacktop.github.io/ipsw/docs/)
    - Join our [Discord server](https://discord.gg/P3ukGGxc)
    - Follow us on [Twitter](https://twitter.com/blacktop__)
