# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    - ./hack/make/completions
    - ./hack/make/manpages
    - ./hack/make/json_mini
builds:
  - main: ./cmd/ipsw
    id: darwin
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - main: ./cmd/ipsw
    id: ios
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - ios
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  # - main: ./cmd/ipsw
  #   id: "others"
  #   binary: ipsw
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - linux
  #     - windows
  #   goarch:
  #     - amd64
  #     - arm64
  #   mod_timestamp: "{{ .CommitTimestamp }}"
  #   flags:
  #     - -trimpath
  #   ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
universal_binaries:
  - id: darwin
    replace: false
archives:
  - replacements:
      darwin: macOS
      # ios: iOS
      amd64: x86_64
      all: universal
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*
    wrap_in_directory: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/ipsw"
    description: "iOS/macOS Research Swiss Army Knife"
    license: MIT
    dependencies:
      - name: bat
        type: optional
    install: |
      bin.install "ipsw"
      bash_completion.install "completions/_bash" => "ipsw"
      zsh_completion.install "completions/_zsh" => "_ipsw"
      fish_completion.install "completions/_fish" => "ipsw.fish"
      man1.install Dir["manpages/*"]
    test: |
      system "#{bin}/ipsw --version"
checksum:
  name_template: "checksums.darwin.txt"
signs:
  - artifacts: checksum
sboms:
  - artifacts: archive
changelog:
  sort: asc
  use: github
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: Dependency updates
      regexp: "^.*chore\\(deps\\)*:+.*$"
      order: 300
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "^Delete"
      - "^Working"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/ipsw/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Read the [documentation](https://blacktop.github.io/ipsw/docs/)
    - Join our [Discord server](https://discord.gg/M5Wqf6JT)
    - Follow us on [Twitter](https://twitter.com/blacktop__)

announce:
  skip: "{{gt .Patch 0}}"

  twitter:
    enabled: true
    message_template: "ipsw {{ .Tag }} is out! Check it out: https://github.com/blacktop/ipsw/releases/tag/{{ .Tag }}"
