package macho

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteHeaderIncludesBoilerplateByDefault(t *testing.T) {
	t.Parallel()

	outPath := filepath.Join(t.TempDir(), "Foo.h")
	err := writeHeader(&headerInfo{
		FileName:      outPath,
		IpswVersion:   "Version: 1.2.3, BuildCommit: deadbeef",
		BuildVersions: []string{"platform iOS, min 17.0, sdk 17.4"},
		SourceVersion: "123.45.6",
		Name:          "Foo",
		Object:        "@interface Foo : NSObject\n@end",
	})
	if err != nil {
		t.Fatalf("writeHeader failed: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read generated header: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "Generated by https://github.com/blacktop/ipsw") {
		t.Fatalf("expected autogenerated comment block, got:\n%s", content)
	}
	if !strings.Contains(content, "LC_BUILD_VERSION") {
		t.Fatalf("expected build metadata comments, got:\n%s", content)
	}
	if !strings.Contains(content, "#ifndef Foo_h") || !strings.Contains(content, "#define Foo_h") {
		t.Fatalf("expected include guards, got:\n%s", content)
	}
}

func TestWriteHeaderNoCommentsOmitsBoilerplate(t *testing.T) {
	t.Parallel()

	outPath := filepath.Join(t.TempDir(), "Bar.h")
	err := writeHeader(&headerInfo{
		FileName:         outPath,
		IpswVersion:      "Version: 9.9.9, BuildCommit: cafebabe",
		BuildVersions:    []string{"platform iOS, min 17.0, sdk 17.4"},
		SourceVersion:    "987.65.4",
		NoHeaderComments: true,
		Name:             "Bar",
		Object:           "@interface Bar : NSObject\n@end",
	})
	if err != nil {
		t.Fatalf("writeHeader failed: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read generated header: %v", err)
	}
	content := string(data)

	if strings.Contains(content, "Generated by https://github.com/blacktop/ipsw") {
		t.Fatalf("expected autogenerated comment block to be omitted, got:\n%s", content)
	}
	if strings.Contains(content, "LC_BUILD_VERSION") || strings.Contains(content, "LC_SOURCE_VERSION") {
		t.Fatalf("expected metadata comments to be omitted, got:\n%s", content)
	}
	if !strings.HasPrefix(content, "#ifndef Bar_h\n#define Bar_h\n") {
		t.Fatalf("expected header to start with include guards, got:\n%s", content)
	}
}
