// Code generated by "stringer -type=reType -output regex_string.go"; DO NOT EDIT.

package sandbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Character-0]
	_ = x[JumpForward-1]
	_ = x[JumpBackward-2]
	_ = x[Class-3]
	_ = x[ClassExclude-4]
	_ = x[End-5]
	_ = x[Terminator-6]
}

const _reType_name = "CharacterJumpForwardJumpBackwardClassClassExcludeEndTerminator"

var _reType_index = [...]uint8{0, 9, 20, 32, 37, 49, 52, 62}

func (i reType) String() string {
	if i < 0 || i >= reType(len(_reType_index)-1) {
		return "reType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _reType_name[_reType_index[i]:_reType_index[i+1]]
}
