// Code generated by "stringer -type=platform"; DO NOT EDIT.

package dyld

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[macOS-1]
	_ = x[iOS-2]
	_ = x[tvOS-3]
	_ = x[watchOS-4]
	_ = x[bridgeOS-5]
	_ = x[iOSMac-6]
	_ = x[iOSSimulator-7]
	_ = x[tvOSSimulator-8]
	_ = x[watchOSSimulator-9]
}

const _platform_name = "unknownmacOSiOStvOSwatchOSbridgeOSiOSMaciOSSimulatortvOSSimulatorwatchOSSimulator"

var _platform_index = [...]uint8{0, 7, 12, 15, 19, 26, 34, 40, 52, 65, 81}

func (i platform) String() string {
	if i >= platform(len(_platform_index)-1) {
		return "platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _platform_name[_platform_index[i]:_platform_index[i+1]]
}
