// Code generated by "stringer -type=dyld_section_location_kind -trimprefix=dyld_section_location_ -output prebuilt_string.go"; DO NOT EDIT.

package dyld

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dyld_section_location_text_swift5_protos-0]
	_ = x[dyld_section_location_text_swift5_proto-1]
	_ = x[dyld_section_location_text_swift5_types-2]
	_ = x[dyld_section_location_text_swift5_replace-3]
	_ = x[dyld_section_location_text_swift5_replace2-4]
	_ = x[dyld_section_location_text_swift5_ac_funcs-5]
	_ = x[dyld_section_location_objc_image_info-6]
	_ = x[dyld_section_location_data_sel_refs-7]
	_ = x[dyld_section_location_data_msg_refs-8]
	_ = x[dyld_section_location_data_class_refs-9]
	_ = x[dyld_section_location_data_super_refs-10]
	_ = x[dyld_section_location_data_protocol_refs-11]
	_ = x[dyld_section_location_data_class_list-12]
	_ = x[dyld_section_location_data_non_lazy_class_list-13]
	_ = x[dyld_section_location_data_stub_list-14]
	_ = x[dyld_section_location_data_category_list-15]
	_ = x[dyld_section_location_data_category_list2-16]
	_ = x[dyld_section_location_data_non_lazy_category_list-17]
	_ = x[dyld_section_location_data_protocol_list-18]
	_ = x[dyld_section_location_data_objc_fork_ok-19]
	_ = x[dyld_section_location_data_raw_isa-20]
	_ = x[dyld_section_location_count-21]
}

const _dyld_section_location_kind_name = "text_swift5_protostext_swift5_prototext_swift5_typestext_swift5_replacetext_swift5_replace2text_swift5_ac_funcsobjc_image_infodata_sel_refsdata_msg_refsdata_class_refsdata_super_refsdata_protocol_refsdata_class_listdata_non_lazy_class_listdata_stub_listdata_category_listdata_category_list2data_non_lazy_category_listdata_protocol_listdata_objc_fork_okdata_raw_isacount"

var _dyld_section_location_kind_index = [...]uint16{0, 18, 35, 52, 71, 91, 111, 126, 139, 152, 167, 182, 200, 215, 239, 253, 271, 290, 317, 335, 352, 364, 369}

func (i dyld_section_location_kind) String() string {
	if i >= dyld_section_location_kind(len(_dyld_section_location_kind_index)-1) {
		return "dyld_section_location_kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dyld_section_location_kind_name[_dyld_section_location_kind_index[i]:_dyld_section_location_kind_index[i+1]]
}
