// Code generated by "stringer -type=j_obj_types,j_obj_kinds,j_inode_flags,dir_rec_flags,apfs_mode_t,dir_ent_file_type -output j_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APFS_TYPE_ANY-0]
	_ = x[APFS_TYPE_SNAP_METADATA-1]
	_ = x[APFS_TYPE_EXTENT-2]
	_ = x[APFS_TYPE_INODE-3]
	_ = x[APFS_TYPE_XATTR-4]
	_ = x[APFS_TYPE_SIBLING_LINK-5]
	_ = x[APFS_TYPE_DSTREAM_ID-6]
	_ = x[APFS_TYPE_CRYPTO_STATE-7]
	_ = x[APFS_TYPE_FILE_EXTENT-8]
	_ = x[APFS_TYPE_DIR_REC-9]
	_ = x[APFS_TYPE_DIR_STATS-10]
	_ = x[APFS_TYPE_SNAP_NAME-11]
	_ = x[APFS_TYPE_SIBLING_MAP-12]
	_ = x[APFS_TYPE_FILE_INFO-13]
	_ = x[APFS_TYPE_MAX_VALID-13]
	_ = x[APFS_TYPE_MAX-15]
	_ = x[APFS_TYPE_INVALID-15]
}

const (
	_j_obj_types_name_0 = "APFS_TYPE_ANYAPFS_TYPE_SNAP_METADATAAPFS_TYPE_EXTENTAPFS_TYPE_INODEAPFS_TYPE_XATTRAPFS_TYPE_SIBLING_LINKAPFS_TYPE_DSTREAM_IDAPFS_TYPE_CRYPTO_STATEAPFS_TYPE_FILE_EXTENTAPFS_TYPE_DIR_RECAPFS_TYPE_DIR_STATSAPFS_TYPE_SNAP_NAMEAPFS_TYPE_SIBLING_MAPAPFS_TYPE_FILE_INFO"
	_j_obj_types_name_1 = "APFS_TYPE_MAX"
)

var (
	_j_obj_types_index_0 = [...]uint16{0, 13, 36, 52, 67, 82, 104, 124, 146, 167, 184, 203, 222, 243, 262}
)

func (i j_obj_types) String() string {
	switch {
	case i <= 13:
		return _j_obj_types_name_0[_j_obj_types_index_0[i]:_j_obj_types_index_0[i+1]]
	case i == 15:
		return _j_obj_types_name_1
	default:
		return "j_obj_types(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APFS_KIND_ANY-0]
	_ = x[APFS_KIND_NEW-1]
	_ = x[APFS_KIND_UPDATE-2]
	_ = x[APFS_KIND_DEAD-3]
	_ = x[APFS_KIND_UPDATE_RECENT-4]
	_ = x[APFS_KIND_INVALID-255]
}

const (
	_j_obj_kinds_name_0 = "APFS_KIND_ANYAPFS_KIND_NEWAPFS_KIND_UPDATEAPFS_KIND_DEADAPFS_KIND_UPDATE_RECENT"
	_j_obj_kinds_name_1 = "APFS_KIND_INVALID"
)

var (
	_j_obj_kinds_index_0 = [...]uint8{0, 13, 26, 42, 56, 79}
)

func (i j_obj_kinds) String() string {
	switch {
	case i <= 4:
		return _j_obj_kinds_name_0[_j_obj_kinds_index_0[i]:_j_obj_kinds_index_0[i+1]]
	case i == 255:
		return _j_obj_kinds_name_1
	default:
		return "j_obj_kinds(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INODE_IS_APFS_PRIVATE-1]
	_ = x[INODE_MAINTAIN_DIR_STATS-2]
	_ = x[INODE_DIR_STATS_ORIGIN-4]
	_ = x[INODE_PROT_CLASS_EXPLICIT-8]
	_ = x[INODE_WAS_CLONED-16]
	_ = x[INODE_FLAG_UNUSED-32]
	_ = x[INODE_HAS_SECURITY_EA-64]
	_ = x[INODE_BEING_TRUNCATED-128]
	_ = x[INODE_HAS_FINDER_INFO-256]
	_ = x[INODE_IS_SPARSE-512]
	_ = x[INODE_WAS_EVER_CLONED-1024]
	_ = x[INODE_ACTIVE_FILE_TRIMMED-2048]
	_ = x[INODE_PINNED_TO_MAIN-4096]
	_ = x[INODE_PINNED_TO_TIER2-8192]
	_ = x[INODE_HAS_RSRC_FORK-16384]
	_ = x[INODE_NO_RSRC_FORK-32768]
	_ = x[INODE_ALLOCATION_SPILLEDOVER-65536]
	_ = x[INODE_FAST_PROMOTE-131072]
	_ = x[INODE_HAS_UNCOMPRESSED_SIZE-262144]
	_ = x[INODE_IS_PURGEABLE-524288]
	_ = x[INODE_WANTS_TO_BE_PURGEABLE-1048576]
	_ = x[INODE_IS_SYNC_ROOT-2097152]
	_ = x[INODE_SNAPSHOT_COW_EXEMPTION-4194304]
	_ = x[INODE_INHERITED_INTERNAL_FLAGS-4194306]
	_ = x[INODE_CLONED_INTERNAL_FLAGS-4243712]
	_ = x[APFS_VALID_INTERNAL_INODE_FLAGS-8388575]
	_ = x[APFS_INODE_PINNED_MASK-12288]
}

const _j_inode_flags_name = "INODE_IS_APFS_PRIVATEINODE_MAINTAIN_DIR_STATSINODE_DIR_STATS_ORIGININODE_PROT_CLASS_EXPLICITINODE_WAS_CLONEDINODE_FLAG_UNUSEDINODE_HAS_SECURITY_EAINODE_BEING_TRUNCATEDINODE_HAS_FINDER_INFOINODE_IS_SPARSEINODE_WAS_EVER_CLONEDINODE_ACTIVE_FILE_TRIMMEDINODE_PINNED_TO_MAININODE_PINNED_TO_TIER2APFS_INODE_PINNED_MASKINODE_HAS_RSRC_FORKINODE_NO_RSRC_FORKINODE_ALLOCATION_SPILLEDOVERINODE_FAST_PROMOTEINODE_HAS_UNCOMPRESSED_SIZEINODE_IS_PURGEABLEINODE_WANTS_TO_BE_PURGEABLEINODE_IS_SYNC_ROOTINODE_SNAPSHOT_COW_EXEMPTIONINODE_INHERITED_INTERNAL_FLAGSINODE_CLONED_INTERNAL_FLAGSAPFS_VALID_INTERNAL_INODE_FLAGS"

var _j_inode_flags_map = map[j_inode_flags]string{
	1:       _j_inode_flags_name[0:21],
	2:       _j_inode_flags_name[21:45],
	4:       _j_inode_flags_name[45:67],
	8:       _j_inode_flags_name[67:92],
	16:      _j_inode_flags_name[92:108],
	32:      _j_inode_flags_name[108:125],
	64:      _j_inode_flags_name[125:146],
	128:     _j_inode_flags_name[146:167],
	256:     _j_inode_flags_name[167:188],
	512:     _j_inode_flags_name[188:203],
	1024:    _j_inode_flags_name[203:224],
	2048:    _j_inode_flags_name[224:249],
	4096:    _j_inode_flags_name[249:269],
	8192:    _j_inode_flags_name[269:290],
	12288:   _j_inode_flags_name[290:312],
	16384:   _j_inode_flags_name[312:331],
	32768:   _j_inode_flags_name[331:349],
	65536:   _j_inode_flags_name[349:377],
	131072:  _j_inode_flags_name[377:395],
	262144:  _j_inode_flags_name[395:422],
	524288:  _j_inode_flags_name[422:440],
	1048576: _j_inode_flags_name[440:467],
	2097152: _j_inode_flags_name[467:485],
	4194304: _j_inode_flags_name[485:513],
	4194306: _j_inode_flags_name[513:543],
	4243712: _j_inode_flags_name[543:570],
	8388575: _j_inode_flags_name[570:601],
}

func (i j_inode_flags) String() string {
	if str, ok := _j_inode_flags_map[i]; ok {
		return str
	}
	return "j_inode_flags(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DREC_TYPE_MASK-15]
	_ = x[RESERVED_10-16]
}

const _dir_rec_flags_name = "DREC_TYPE_MASKRESERVED_10"

var _dir_rec_flags_index = [...]uint8{0, 14, 25}

func (i dir_rec_flags) String() string {
	i -= 15
	if i >= dir_rec_flags(len(_dir_rec_flags_index)-1) {
		return "dir_rec_flags(" + strconv.FormatInt(int64(i+15), 10) + ")"
	}
	return _dir_rec_flags_name[_dir_rec_flags_index[i]:_dir_rec_flags_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[S_IFIFO-4096]
	_ = x[S_IFCHR-8192]
	_ = x[S_IFDIR-16384]
	_ = x[S_IFBLK-24576]
	_ = x[S_IFREG-32768]
	_ = x[S_IFLNK-40960]
	_ = x[S_IFSOCK-49152]
	_ = x[S_IFWHT-57344]
}

const (
	_apfs_mode_t_name_0 = "S_IFIFO"
	_apfs_mode_t_name_1 = "S_IFCHR"
	_apfs_mode_t_name_2 = "S_IFDIR"
	_apfs_mode_t_name_3 = "S_IFBLK"
	_apfs_mode_t_name_4 = "S_IFREG"
	_apfs_mode_t_name_5 = "S_IFLNK"
	_apfs_mode_t_name_6 = "S_IFSOCK"
	_apfs_mode_t_name_7 = "S_IFWHT"
)

func (i apfs_mode_t) String() string {
	switch {
	case i == 4096:
		return _apfs_mode_t_name_0
	case i == 8192:
		return _apfs_mode_t_name_1
	case i == 16384:
		return _apfs_mode_t_name_2
	case i == 24576:
		return _apfs_mode_t_name_3
	case i == 32768:
		return _apfs_mode_t_name_4
	case i == 40960:
		return _apfs_mode_t_name_5
	case i == 49152:
		return _apfs_mode_t_name_6
	case i == 57344:
		return _apfs_mode_t_name_7
	default:
		return "apfs_mode_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DT_UNKNOWN-0]
	_ = x[DT_FIFO-1]
	_ = x[DT_CHR-2]
	_ = x[DT_DIR-4]
	_ = x[DT_BLK-6]
	_ = x[DT_REG-8]
	_ = x[DT_LNK-10]
	_ = x[DT_SOCK-12]
	_ = x[DT_WHT-14]
}

const (
	_dir_ent_file_type_name_0 = "DT_UNKNOWNDT_FIFODT_CHR"
	_dir_ent_file_type_name_1 = "DT_DIR"
	_dir_ent_file_type_name_2 = "DT_BLK"
	_dir_ent_file_type_name_3 = "DT_REG"
	_dir_ent_file_type_name_4 = "DT_LNK"
	_dir_ent_file_type_name_5 = "DT_SOCK"
	_dir_ent_file_type_name_6 = "DT_WHT"
)

var (
	_dir_ent_file_type_index_0 = [...]uint8{0, 10, 17, 23}
)

func (i dir_ent_file_type) String() string {
	switch {
	case i <= 2:
		return _dir_ent_file_type_name_0[_dir_ent_file_type_index_0[i]:_dir_ent_file_type_index_0[i+1]]
	case i == 4:
		return _dir_ent_file_type_name_1
	case i == 6:
		return _dir_ent_file_type_name_2
	case i == 8:
		return _dir_ent_file_type_name_3
	case i == 10:
		return _dir_ent_file_type_name_4
	case i == 12:
		return _dir_ent_file_type_name_5
	case i == 14:
		return _dir_ent_file_type_name_6
	default:
		return "dir_ent_file_type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
