// Code generated by "stringer -type=xfType,xfFlag -output xf_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INO_EXT_TYPE_SNAP_XID-1]
	_ = x[INO_EXT_TYPE_DELTA_TREE_OID-2]
	_ = x[INO_EXT_TYPE_DOCUMENT_ID-3]
	_ = x[INO_EXT_TYPE_NAME-4]
	_ = x[INO_EXT_TYPE_PREV_FSIZE-5]
	_ = x[INO_EXT_TYPE_RESERVED_6-6]
	_ = x[INO_EXT_TYPE_FINDER_INFO-7]
	_ = x[INO_EXT_TYPE_DSTREAM-8]
	_ = x[INO_EXT_TYPE_RESERVED_9-9]
	_ = x[INO_EXT_TYPE_DIR_STATS_KEY-10]
	_ = x[INO_EXT_TYPE_FS_UUID-11]
	_ = x[INO_EXT_TYPE_RESERVED_12-12]
	_ = x[INO_EXT_TYPE_SPARSE_BYTES-13]
	_ = x[INO_EXT_TYPE_RDEV-14]
	_ = x[INO_EXT_TYPE_PURGEABLE_FLAGS-15]
	_ = x[INO_EXT_TYPE_ORIG_SYNC_ROOT_ID-16]
}

const _xfType_name = "INO_EXT_TYPE_SNAP_XIDINO_EXT_TYPE_DELTA_TREE_OIDINO_EXT_TYPE_DOCUMENT_IDINO_EXT_TYPE_NAMEINO_EXT_TYPE_PREV_FSIZEINO_EXT_TYPE_RESERVED_6INO_EXT_TYPE_FINDER_INFOINO_EXT_TYPE_DSTREAMINO_EXT_TYPE_RESERVED_9INO_EXT_TYPE_DIR_STATS_KEYINO_EXT_TYPE_FS_UUIDINO_EXT_TYPE_RESERVED_12INO_EXT_TYPE_SPARSE_BYTESINO_EXT_TYPE_RDEVINO_EXT_TYPE_PURGEABLE_FLAGSINO_EXT_TYPE_ORIG_SYNC_ROOT_ID"

var _xfType_index = [...]uint16{0, 21, 48, 72, 89, 112, 135, 159, 179, 202, 228, 248, 272, 297, 314, 342, 372}

func (i xfType) String() string {
	i -= 1
	if i >= xfType(len(_xfType_index)-1) {
		return "xfType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _xfType_name[_xfType_index[i]:_xfType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[XF_DATA_DEPENDENT-1]
	_ = x[XF_DO_NOT_COPY-2]
	_ = x[XF_RESERVED_4-4]
	_ = x[XF_CHILDREN_INHERIT-8]
	_ = x[XF_USER_FIELD-16]
	_ = x[XF_SYSTEM_FIELD-32]
	_ = x[XF_RESERVED_40-64]
	_ = x[XF_RESERVED_80-128]
}

const (
	_xfFlag_name_0 = "XF_DATA_DEPENDENTXF_DO_NOT_COPY"
	_xfFlag_name_1 = "XF_RESERVED_4"
	_xfFlag_name_2 = "XF_CHILDREN_INHERIT"
	_xfFlag_name_3 = "XF_USER_FIELD"
	_xfFlag_name_4 = "XF_SYSTEM_FIELD"
	_xfFlag_name_5 = "XF_RESERVED_40"
	_xfFlag_name_6 = "XF_RESERVED_80"
)

var (
	_xfFlag_index_0 = [...]uint8{0, 17, 31}
)

func (i xfFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _xfFlag_name_0[_xfFlag_index_0[i]:_xfFlag_index_0[i+1]]
	case i == 4:
		return _xfFlag_name_1
	case i == 8:
		return _xfFlag_name_2
	case i == 16:
		return _xfFlag_name_3
	case i == 32:
		return _xfFlag_name_4
	case i == 64:
		return _xfFlag_name_5
	case i == 128:
		return _xfFlag_name_6
	default:
		return "xfFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
