package car

import (
	"bytes"
	"compress/zlib"
	"encoding/binary"
	"fmt"
	"hash/crc32"
	"image"
	"image/png"
	"io"
	"math"
	"unicode/utf16"
)

// encodePNG preserves sample values and tags known source color spaces. Generic
// and unknown spaces remain untagged rather than guessing that they are sRGB.
// Extended profiles describe only PNG's normalized integer range: this encoder
// cannot recover floating-point values clipped by a preceding image conversion.
func encodePNG(w io.Writer, img image.Image, space colorSpaceID) error {
	if space < SRGB || space > ExtendedGray {
		return png.Encode(w, img)
	}
	return png.Encode(&profilePNGWriter{dst: w, space: space}, img)
}

// Buffer only the signature and IHDR. Reading the actual PNG color type avoids
// attaching a grayscale ICC profile to an RGB image (including gray+alpha
// images, which image/png writes as RGB+alpha).
type profilePNGWriter struct {
	dst    io.Writer
	space  colorSpaceID
	header [33]byte
	n      int
}

func (w *profilePNGWriter) Write(p []byte) (int, error) {
	consumed := 0
	if w.n < len(w.header) {
		consumed = copy(w.header[w.n:], p)
		w.n += consumed
		p = p[consumed:]
		if w.n < len(w.header) {
			return consumed, nil
		}
		if string(w.header[:8]) != "\x89PNG\r\n\x1a\n" ||
			binary.BigEndian.Uint32(w.header[8:12]) != 13 || string(w.header[12:16]) != "IHDR" {
			return consumed, fmt.Errorf("invalid PNG header from encoder")
		}
		if err := writePNGBytes(w.dst, w.header[:]); err != nil {
			return consumed, err
		}
		gray := w.header[25] == 0 || w.header[25] == 4
		profile := pngColorProfile(w.space, gray)
		var compressed bytes.Buffer
		zw := zlib.NewWriter(&compressed)
		if _, err := zw.Write(profile); err != nil {
			return consumed, err
		}
		if err := zw.Close(); err != nil {
			return consumed, err
		}
		data := append([]byte("ipsw source color\x00\x00"), compressed.Bytes()...)
		chunk := make([]byte, 12+len(data))
		binary.BigEndian.PutUint32(chunk, uint32(len(data)))
		copy(chunk[4:8], "iCCP")
		copy(chunk[8:], data)
		binary.BigEndian.PutUint32(chunk[8+len(data):], crc32.ChecksumIEEE(chunk[4:8+len(data)]))
		if err := writePNGBytes(w.dst, chunk); err != nil {
			return consumed, err
		}
	}
	n, err := w.dst.Write(p)
	if err == nil && n != len(p) {
		err = io.ErrShortWrite
	}
	return consumed + n, err
}

func writePNGBytes(w io.Writer, data []byte) error {
	n, err := w.Write(data)
	if err == nil && n != len(data) {
		return io.ErrShortWrite
	}
	return err
}

// pngColorProfile constructs ICC v4 matrix/TRC display profiles from published
// colorimetry, without embedding profiles copied from a host operating system.
// Profile layout: https://www.color.org/specification/ICC.1-2022-05.pdf
// Primaries/transfers: https://www.w3.org/TR/css-color-4/#predefined
// D65 -> D50 adaptation: https://www.color.org/chadtag/
func pngColorProfile(space colorSpaceID, gray bool) []byte {
	if space < SRGB || space > ExtendedGray {
		return nil
	}
	description := space.String()
	if space == ExtendedSRGB || space == ExtendedLinear || space == ExtendedGray {
		description += " (normalized PNG range)"
	}
	// ICC parametric curve type 3: Y=(aX+b)^g above d, otherwise Y=cX.
	trc := iccCurve(3, 2.4, 1/1.055, 0.055/1.055, 1/12.92, 0.04045)
	switch space {
	case Mono, ExtendedGray:
		// CoreUI's GenericGrayGamma2_2 and ExtendedGray profiles use the
		// sRGB piecewise curve, despite their gamma-2.2 names. This matches
		// the native ICC kTRC and CoreUI grayscale-to-RGB rendering.
	case ExtendedLinear:
		trc = iccCurve(0, 1)
	}
	adapt := [3][3]float64{
		{1.04790738171017, 0.0229333845542104, -0.0502016347980104},
		{0.0296059594177168, 0.990456039910785, -0.01707552919587},
		{-0.00924679432678241, 0.0150626801401488, 0.751791232609078},
	}
	type tag struct {
		name string
		data []byte
	}
	tags := []tag{
		{"desc", iccText(description)},
		{"cprt", iccText("Color profile generated by ipsw from standard colorimetry.")},
		{"wtpt", iccNumbers("XYZ ", 0.9642, 1, 0.8249)},
		{"chad", iccNumbers("sf32", adapt[0][0], adapt[0][1], adapt[0][2],
			adapt[1][0], adapt[1][1], adapt[1][2], adapt[2][0], adapt[2][1], adapt[2][2])},
	}
	if gray {
		tags = append(tags, tag{"kTRC", trc})
	} else {
		// Linear RGB -> XYZ under D65. Gray samples expanded to RGB use equal
		// channels with their original gamma, so these primaries preserve gray.
		matrix := [3][3]float64{
			{0.41239079926596, 0.35758433938388, 0.18048078840183},
			{0.21263900587151, 0.71516867876776, 0.07219231536073},
			{0.01933081871559, 0.11919477979463, 0.95053215224966},
		}
		if space == DisplayP3 {
			matrix = [3][3]float64{
				{0.48657094864822, 0.26566769316909, 0.19821728523436},
				{0.22897456406975, 0.69173852183651, 0.07928691409375},
				{0, 0.04511338185890, 1.04394436890098},
			}
		}
		for channel, name := range []string{"rXYZ", "gXYZ", "bXYZ"} {
			var xyz [3]float64
			for row := range 3 {
				for col := range 3 {
					xyz[row] += adapt[row][col] * matrix[col][channel]
				}
			}
			tags = append(tags, tag{name, iccNumbers("XYZ ", xyz[:]...)})
		}
		for _, name := range []string{"rTRC", "gTRC", "bTRC"} {
			tags = append(tags, tag{name, trc})
		}
	}
	profile := make([]byte, 132+12*len(tags))
	binary.BigEndian.PutUint32(profile[8:12], 0x04400000)
	copy(profile[12:16], "mntr")
	copy(profile[16:20], "RGB ")
	if gray {
		copy(profile[16:20], "GRAY")
	}
	copy(profile[20:24], "XYZ ")
	// Fixed creation date makes independently exported variants deterministic.
	for i, v := range []uint16{2026, 1, 1, 0, 0, 0} {
		binary.BigEndian.PutUint16(profile[24+i*2:], v)
	}
	copy(profile[36:40], "acsp")
	binary.BigEndian.PutUint32(profile[64:68], 1) // relative colorimetric intent
	copy(profile[68:80], iccNumbers("XYZ ", 0.9642, 1, 0.8249)[8:])
	binary.BigEndian.PutUint32(profile[128:132], uint32(len(tags)))
	for i, tag := range tags {
		entry := profile[132+12*i:][:12]
		copy(entry, tag.name)
		binary.BigEndian.PutUint32(entry[4:8], uint32(len(profile)))
		binary.BigEndian.PutUint32(entry[8:12], uint32(len(tag.data)))
		profile = append(profile, tag.data...)
		for len(profile)%4 != 0 {
			profile = append(profile, 0)
		}
	}
	binary.BigEndian.PutUint32(profile, uint32(len(profile)))
	return profile
}

func iccNumbers(signature string, values ...float64) []byte {
	data := make([]byte, 8+4*len(values))
	copy(data, signature)
	for i, value := range values {
		binary.BigEndian.PutUint32(data[8+4*i:], uint32(int32(math.Round(value*65536))))
	}
	return data
}

func iccCurve(function uint16, parameters ...float64) []byte {
	data := make([]byte, 12+4*len(parameters))
	copy(data, "para")
	binary.BigEndian.PutUint16(data[8:10], function)
	copy(data[12:], iccNumbers("", parameters...)[8:])
	return data
}

func iccText(text string) []byte {
	characters := utf16.Encode([]rune(text))
	data := make([]byte, 28+2*len(characters))
	copy(data, "mluc")
	binary.BigEndian.PutUint32(data[8:12], 1)
	binary.BigEndian.PutUint32(data[12:16], 12)
	copy(data[16:20], "enUS")
	binary.BigEndian.PutUint32(data[20:24], uint32(2*len(characters)))
	binary.BigEndian.PutUint32(data[24:28], 28)
	for i, c := range characters {
		binary.BigEndian.PutUint16(data[28+2*i:], c)
	}
	return data
}
