// Code generated by "stringer -type=Orientation -output springboard_string.go"; DO NOT EDIT.

package springboard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Portrait-1]
	_ = x[PortraitUpsideDown-2]
	_ = x[Landscape-3]
	_ = x[LandscapeHomeToLeft-4]
}

const _Orientation_name = "UnknownPortraitPortraitUpsideDownLandscapeLandscapeHomeToLeft"

var _Orientation_index = [...]uint8{0, 7, 15, 33, 42, 61}

func (i Orientation) String() string {
	if i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
