# This is an example pipeline.yml file with some sensible defaults.
# Make sure to check the documentation at https://blacktop.github.io/ipsw
downloads:
  ipsws:
    - id: ipsw
      devices:
        - iPhone14,2
        - iPhone15,2
      latest: true
  otas:
    - id: ota
      devices:
        - iPhone14,2
        - iPhone15,2
      beta: true

extracts:
  - ids:
      - ipsw
    kernelcache: true
    dyld_shared_cache: true
  - ids:
      - ota
    kernelcache: true
    dyld_shared_cache: true
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://raw.githubusercontent.com/blacktop/ipsw/master/internal/pipeline/static/schema/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
