// Code generated by "stringer -type=SubsystemStart -output mig_string.go"; DO NOT EDIT.

package kernelcache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[arcade_register_subsystem-51471]
	_ = x[catch_exc_subsystem-2401]
	_ = x[catch_mach_exc_subsystem-2405]
	_ = x[clock_subsystem-1000]
	_ = x[host_priv_subsystem-400]
	_ = x[is_iokit_subsystem-2800]
	_ = x[mach_eventlink_subsystem-716200]
	_ = x[mach_host_subsystem-200]
	_ = x[mach_port_subsystem-3200]
	_ = x[mach_vm_subsystem-4800]
	_ = x[mach_voucher_subsystem-5400]
	_ = x[memory_entry_subsystem-4900]
	_ = x[processor_set_subsystem-4000]
	_ = x[processor_subsystem-3000]
	_ = x[task_restartable_subsystem-8000]
	_ = x[task_subsystem-3400]
	_ = x[thread_act_subsystem-3600]
	_ = x[UNDReply_subsystem-6200]
	_ = x[vm32_map_subsystem-3800]
}

const _SubsystemStart_name = "mach_host_subsystemhost_priv_subsystemclock_subsystemcatch_exc_subsystemcatch_mach_exc_subsystemis_iokit_subsystemprocessor_subsystemmach_port_subsystemtask_subsystemthread_act_subsystemvm32_map_subsystemprocessor_set_subsystemmach_vm_subsystemmemory_entry_subsystemmach_voucher_subsystemUNDReply_subsystemtask_restartable_subsystemarcade_register_subsystemmach_eventlink_subsystem"

var _SubsystemStart_map = map[SubsystemStart]string{
	200:    _SubsystemStart_name[0:19],
	400:    _SubsystemStart_name[19:38],
	1000:   _SubsystemStart_name[38:53],
	2401:   _SubsystemStart_name[53:72],
	2405:   _SubsystemStart_name[72:96],
	2800:   _SubsystemStart_name[96:114],
	3000:   _SubsystemStart_name[114:133],
	3200:   _SubsystemStart_name[133:152],
	3400:   _SubsystemStart_name[152:166],
	3600:   _SubsystemStart_name[166:186],
	3800:   _SubsystemStart_name[186:204],
	4000:   _SubsystemStart_name[204:227],
	4800:   _SubsystemStart_name[227:244],
	4900:   _SubsystemStart_name[244:266],
	5400:   _SubsystemStart_name[266:288],
	6200:   _SubsystemStart_name[288:306],
	8000:   _SubsystemStart_name[306:332],
	51471:  _SubsystemStart_name[332:357],
	716200: _SubsystemStart_name[357:381],
}

func (i SubsystemStart) String() string {
	if str, ok := _SubsystemStart_map[i]; ok {
		return str
	}
	return "SubsystemStart(" + strconv.FormatInt(int64(i), 10) + ")"
}
