#!/bin/sh
set -e
rm -rf completions
for sh in bash zsh fish powershell; do
	for tool in ipsw ipswd; do
		mkdir -p completions/$sh
		case $sh in
			bash)
				dst=$tool
				;;
			zsh)
				dst=_$tool
				;;
			fish)
				dst=$tool.fish
				;;
			powershell)
				dst=$tool.psm1
				;;
			*)
				echo Unknown shell $sh
				exit 1
				;;
		esac
		go run ./cmd/$tool/main.go completion "$sh" >"completions/$sh/$dst"
	done
done
