#!/bin/sh
set -e
rm -rf completions
mkdir -p completions/{ipsw,ipswd}
for sh in bash zsh fish; do
	go run ./cmd/ipsw/main.go completion "$sh" >"completions/ipsw/_$sh"
done
for sh in bash zsh fish; do
	go run ./cmd/ipswd/main.go completion "$sh" >"completions/ipswd/_$sh"
done
